// apps/docs/.vitepress/theme/components/CopyButton.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { Check, Copy } from 'lucide-vue-next'
import { cn } from '../lib/utils'

interface Props {
    text: string
    iconSize?: number
    class?: string
}

const props = withDefaults(defineProps<Props>(), {
    iconSize: 16,
    class: '',
})

const copied = ref(false)

async function handleCopy() {
    await navigator.clipboard.writeText(props.text)
    copied.value = true
    setTimeout(() => {
        copied.value = false
    }, 2000)
}

const buttonClass = computed(() =>
    cn(
        'inline-flex items-center justify-center border-2 font-bold text-xs transition-all duration-200',
        copied.value
            ? 'border-brutal bg-brutal-secondary text-black'
            : 'border-white bg-gray-800 text-gray-100 hover:border-black hover:bg-brutal-secondary hover:text-black',
        props.class,
    ),
)
</script>

<template>
    <button
        type="button"
        :class="buttonClass"
        :title="copied ? 'Copied!' : 'Copy to clipboard'"
        :aria-label="copied ? 'Copied' : 'Copy to clipboard'"
        @click="handleCopy"
    >
        <Check v-if="copied" :size="iconSize" :stroke-width="2.5" />
        <Copy v-else :size="iconSize" :stroke-width="2.5" />
    </button>
</template>

// apps/docs/components/copy-button.tsx
'use client';

import type * as React from 'react';
import { Check, Copy } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useCopyToClipboard } from '@/hooks/use-copy-to-clipboard';

interface CopyButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    text: string;
    iconSize?: number;
}

export function CopyButton({ text, iconSize = 16, className, ...props }: CopyButtonProps) {
    const { copied, copy } = useCopyToClipboard();
    const Icon = copied ? Check : Copy;

    return (
        <button
            type="button"
            onClick={() => copy(text)}
            className={cn(
                'inline-flex items-center justify-center border-2 font-bold text-xs transition-all duration-200',
                copied
                    ? 'border-black bg-[#4ECDC4] text-black'
                    : 'border-white bg-gray-800 text-gray-100 hover:border-black hover:bg-[#4ECDC4] hover:text-black',
                className
            )}
            title={copied ? 'Copied!' : 'Copy to clipboard'}
            aria-label={copied ? 'Copied' : 'Copy to clipboard'}
            {...props}
        >
            <Icon style={{ width: iconSize, height: iconSize }} strokeWidth={2.5} />
        </button>
    );
}
