// packages/ui/src/components/badge/Badge.vue
<script setup lang="ts">
import { computed } from 'vue'
import { type VariantProps } from 'class-variance-authority'
import { X } from '@lucide/vue'
import { cn } from '@/lib/utils'
import { badgeVariants } from './badge-variants'
import { iconSizeVariants } from '@/lib/icon-size-variants'
import { useLocale } from '@/composables/useLocale'

type BadgeVariantProps = VariantProps<typeof badgeVariants>

interface BadgeProps {
    variant?: NonNullable<BadgeVariantProps['variant']>
    size?: NonNullable<BadgeVariantProps['size']>
    closable?: boolean
    dot?: boolean
    pulse?: boolean
    class?: string
}

const props = withDefaults(defineProps<BadgeProps>(), {
    variant: 'default',
    size: 'default',
    closable: false,
    dot: false,
    pulse: false,
    class: undefined,
})

const emit = defineEmits<{ close: [] }>()

const { t } = useLocale()

const classes = computed(() =>
    cn(badgeVariants({ variant: props.variant, size: props.size }), props.class)
)

const dotClasses = computed(() =>
    cn(
        'rounded-full bg-current',
        props.size === 'sm' ? 'h-1.5 w-1.5 mr-1' : props.size === 'lg' ? 'h-2.5 w-2.5 mr-2' : 'h-2 w-2 mr-1.5',
        props.pulse && 'animate-brutal-badge-pulse'
    )
)

const showDot = computed(() => props.dot || props.pulse)

function handleCloseClick(event: MouseEvent) {
    event.stopPropagation()
    emit('close')
}

const closeIconClasses = computed(() =>
    cn(
        iconSizeVariants({ size: props.size === 'lg' ? 'default' : 'sm' }),
        'stroke-[3]'
    )
)
</script>

<template>
    <span :class="classes">
        <span v-if="showDot" :class="dotClasses" aria-hidden="true" />
        <slot name="icon" />
        <slot />
        <button
            v-if="closable"
            type="button"
            class="ml-1 inline-flex items-center justify-center transition-colors hover:opacity-70 focus:outline-none focus:ring-2 focus:ring-brutal-ring focus:ring-offset-2 rounded-brutal"
            :aria-label="t('badge.close')"
            @click="handleCloseClick"
        >
            <X :class="closeIconClasses" />
        </button>
    </span>
</template>

// packages/ui/src/components/badge.tsx
'use client';

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../lib/utils';

const badgeVariants = cva(
    [
        'inline-flex items-center',
        'border-2 border-brutal rounded-brutal',
        'font-bold tracking-wide',
        'transition-colors',
    ],
    {
        variants: {
            variant: {
                default: [
                    'bg-brutal-bg text-brutal-fg',
                    'shadow-brutal-sm',
                ],
                primary: [
                    'bg-brutal-primary text-brutal-fg',
                    'shadow-brutal-sm',
                ],
                secondary: [
                    'bg-brutal-secondary text-brutal-fg',
                    'shadow-brutal-sm',
                ],
                accent: [
                    'bg-brutal-accent text-brutal-fg',
                    'shadow-brutal-sm',
                ],
                danger: [
                    'bg-brutal-destructive text-brutal-fg',
                    'shadow-brutal-sm',
                ],
                success: [
                    'bg-brutal-success text-brutal-fg',
                    'shadow-brutal-sm',
                ],
                outline: 'bg-transparent text-brutal-fg',
            },
            size: {
                sm: 'px-2 py-0.5 text-xs',
                default: 'px-3 py-1 text-sm',
                lg: 'px-4 py-1.5 text-base',
            },
        },
        defaultVariants: {
            variant: 'default',
            size: 'default',
        },
    }
);

export interface BadgeProps
    extends React.HTMLAttributes<HTMLDivElement>,
        VariantProps<typeof badgeVariants> {}

const Badge = React.forwardRef<HTMLDivElement, BadgeProps>(
    ({ className, variant, size, ...props }, ref) => (
        <div ref={ref} className={cn(badgeVariants({ variant, size, className }))} {...props} />
    )
);
Badge.displayName = 'Badge';

export { Badge, badgeVariants };
