// packages/ui/src/components/Progress.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '../lib/utils'
import { ProgressRoot, ProgressIndicator } from 'reka-ui'

interface ProgressProps {
    class?: string
    modelValue?: number
    max?: number
}

const props = withDefaults(defineProps<ProgressProps>(), {
    modelValue: 0,
    max: 100,
})

const classes = computed(() =>
    cn(
        'relative h-6 w-full overflow-hidden rounded-brutal',
        'border-3 border-brutal bg-white dark:bg-gray-800',
        'shadow-brutal-sm',
        props.class
    )
)

const percentage = computed(() => props.modelValue ?? 0)
</script>

<template>
    <ProgressRoot :class="classes" :model-value="modelValue" :max="max">
        <ProgressIndicator
            class="h-full w-full flex-1 bg-brutal-primary transition-all duration-300 ease-out"
            :style="{ transform: `translateX(-${100 - percentage}%)` }"
        />
    </ProgressRoot>
</template>

// packages/ui/src/components/progress.tsx
'use client';

import * as React from 'react';
import * as ProgressPrimitive from '@radix-ui/react-progress';

import { cn } from '../lib/utils';

const Progress = React.forwardRef<
    React.ElementRef<typeof ProgressPrimitive.Root>,
    React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
    <ProgressPrimitive.Root
        ref={ref}
        value={value}
        className={cn(
            'relative h-6 w-full overflow-hidden rounded-brutal',
            'border-3 border-brutal bg-white dark:bg-gray-800',
            'shadow-brutal-sm',
            className
        )}
        {...props}
    >
        <ProgressPrimitive.Indicator
            className="h-full w-full flex-1 bg-brutal-primary transition-all duration-300 ease-out"
            style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
        />
    </ProgressPrimitive.Root>
));
Progress.displayName = ProgressPrimitive.Root.displayName;

export { Progress };
