// packages/ui/src/components/separator/Separator.vue
<script setup lang="ts">
import { computed } from 'vue'
import { type VariantProps } from 'class-variance-authority'
import { cn } from '../../lib/utils'
import { Separator as SeparatorPrimitive } from 'reka-ui'
import { separatorVariants } from './separator-variants'

type SeparatorVariantProps = VariantProps<typeof separatorVariants>

interface SeparatorProps {
    orientation?: NonNullable<SeparatorVariantProps['orientation']>
    decorative?: boolean
    class?: string
}

const props = withDefaults(defineProps<SeparatorProps>(), {
    orientation: 'horizontal',
    decorative: true,
    class: '',
})

const classes = computed(() =>
    cn(separatorVariants({ orientation: props.orientation }), props.class)
)
</script>

<template>
    <SeparatorPrimitive
        :orientation="orientation"
        :decorative="decorative"
        :class="classes"
    >
        <slot />
    </SeparatorPrimitive>
</template>

// packages/ui/src/components/separator.tsx
import * as React from 'react';
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import { cn } from '../lib/utils';

const Separator = React.forwardRef<
    React.ElementRef<typeof SeparatorPrimitive.Root>,
    React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(
    ({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (
        <SeparatorPrimitive.Root
            ref={ref}
            decorative={decorative}
            orientation={orientation}
            className={cn(
                'shrink-0 bg-black dark:bg-white',
                orientation === 'horizontal' ? 'h-[3px] w-full' : 'h-full w-[3px]',
                className
            )}
            {...props}
        />
    )
);
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };
