// packages/ui/src/components/toast/Toast.vue
<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue'
import { X, CheckCircle, AlertCircle, AlertTriangle, Info, Zap } from '@lucide/vue'
import { type VariantProps } from 'class-variance-authority'
import { cn } from '../../lib/utils'
import { toastVariants } from './toast-variants'
import { useLocale } from '@/composables/useLocale'

type ToastVariantProps = VariantProps<typeof toastVariants>

const DEFAULT_DURATION = 5000
const LEAVE_ANIMATION_DELAY = 300

interface ToastProps {
    variant?: NonNullable<ToastVariantProps['variant']>
    size?: NonNullable<ToastVariantProps['size']>
    title?: string
    description?: string
    duration?: number
    class?: string
}

const props = withDefaults(defineProps<ToastProps>(), {
    variant: 'default',
    size: 'default',
    title: undefined,
    description: undefined,
    duration: DEFAULT_DURATION,
    class: undefined,
})

const emit = defineEmits<{ close: [] }>()

const { t } = useLocale()

const isLeaving = ref(false)
const timer = ref<number | undefined>(undefined)
const leaveTimer = ref<number | undefined>(undefined)

function startLeave() {
    if (isLeaving.value) return
    isLeaving.value = true
    leaveTimer.value = window.setTimeout(() => {
        emit('close')
    }, LEAVE_ANIMATION_DELAY)
}

onMounted(() => {
    if (props.duration) {
        timer.value = window.setTimeout(() => {
            startLeave()
        }, props.duration)
    }
})

onUnmounted(() => {
    if (timer.value) window.clearTimeout(timer.value)
    if (leaveTimer.value) window.clearTimeout(leaveTimer.value)
})

const classes = computed(() =>
    cn(
        toastVariants({ variant: props.variant, size: props.size }),
        isLeaving.value && 'animate-out slide-out-to-right-full fade-out-0',
        props.class
    )
)

const iconComponent = computed(() => {
    switch (props.variant) {
        case 'success': return CheckCircle
        case 'error': return AlertCircle
        case 'warning': return AlertTriangle
        case 'info': return Info
        default: return Zap
    }
})

const closeClasses = computed(() =>
    cn(
        'flex-shrink-0 h-8 w-8 flex items-center justify-center',
        'border-3 border-brutal bg-brutal-bg',
        'shadow-brutal-sm',
        'transition-all duration-150',
        'hover:shadow-brutal-lg hover:-translate-x-0.5 hover:-translate-y-0.5',
        'active:translate-y-[var(--brutal-pressed-offset,2px)] active:shadow-none',
        'focus:outline-none focus:ring-2 focus:ring-brutal-ring focus:ring-offset-2'
    )
)
</script>

<template>
    <div :class="classes" role="alert">
        <div v-if="duration" class="absolute top-0 left-0 right-0 h-1 bg-brutal-fg/10 overflow-hidden">
            <div
                class="h-full bg-brutal-fg/30 animate-nb-shrink"
                :style="{ animationDuration: `${duration}ms` }"
            />
        </div>

        <div class="flex items-start gap-4 p-4 pt-5">
            <div class="flex-shrink-0 mt-0.5">
                <component :is="iconComponent" class="h-6 w-6 stroke-[2.5]" />
            </div>

            <div class="flex-1 min-w-0">
                <p v-if="title" class="font-black text-base leading-tight">
{{ title }}
</p>
                <p v-if="description" class="font-medium text-sm mt-1 opacity-80 leading-snug">
{{ description }}
</p>
                <slot />
            </div>

            <button :class="closeClasses" :aria-label="t('toast.close')" @click="startLeave">
                <X class="h-4 w-4 stroke-[3]" />
            </button>
        </div>
    </div>
</template>

// packages/ui/src/components/toast.tsx
'use client';

import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { X, CheckCircle, AlertCircle, AlertTriangle, Info, Zap } from 'lucide-react';
import { cn } from '../lib/utils';

const toastVariants = cva(
    [
        'pointer-events-auto relative w-full overflow-hidden',
        'border-3 border-brutal',
        'transition-all duration-300 ease-out',
        'animate-in slide-in-from-right-full fade-in-0',
    ],
    {
        variants: {
            variant: {
                default: [
                    'bg-white dark:bg-gray-900 text-black dark:text-white',
                    'shadow-brutal-lg',
                ],
                success: [
                    'bg-[#7FB069] text-black dark:bg-[#2d4a28] dark:text-white',
                    'shadow-brutal-lg',
                ],
                error: [
                    'bg-[#FF6B6B] text-black dark:bg-[#7a2d2d] dark:text-white',
                    'shadow-brutal-lg',
                ],
                warning: [
                    'bg-[#FFE66D] text-black dark:bg-[#6b5a1f] dark:text-white',
                    'shadow-brutal-lg',
                ],
                info: [
                    'bg-[#4ECDC4] text-black dark:bg-[#1f5450] dark:text-white',
                    'shadow-brutal-lg',
                ],
            },
            size: {
                sm: 'max-w-xs',
                default: 'max-w-sm',
                lg: 'max-w-md',
            },
        },
        defaultVariants: {
            variant: 'default',
            size: 'default',
        },
    }
);

export interface ToastProps
    extends React.HTMLAttributes<HTMLDivElement>,
        VariantProps<typeof toastVariants> {
    title?: string;
    description?: string;
    onClose?: () => void;
    icon?: React.ReactNode;
    action?: React.ReactNode;
    duration?: number;
}

const Toast = React.forwardRef<HTMLDivElement, ToastProps>(
    (
        {
            className,
            variant,
            size,
            title,
            description,
            onClose,
            icon,
            action,
            duration = 5000,
            children,
            ...props
        },
        ref
    ) => {
        const [isLeaving, setIsLeaving] = React.useState(false);

        React.useEffect(() => {
            if (duration && onClose) {
                const timer = setTimeout(() => {
                    setIsLeaving(true);
                    setTimeout(() => onClose(), 200);
                }, duration);
                return () => clearTimeout(timer);
            }
            return undefined;
        }, [duration, onClose]);

        const getDefaultIcon = (): React.ReactNode | null => {
            const iconClass = 'h-6 w-6 stroke-[2.5] flex-shrink-0';
            switch (variant) {
                case 'success':
                    return <CheckCircle className={iconClass} />;
                case 'error':
                    return <AlertCircle className={iconClass} />;
                case 'warning':
                    return <AlertTriangle className={iconClass} />;
                case 'info':
                    return <Info className={iconClass} />;
                default:
                    return <Zap className={iconClass} />;
            }
        };

        const defaultIcon = getDefaultIcon();

        return (
            <div
                ref={ref}
                className={cn(
                    toastVariants({ variant, size }),
                    isLeaving && 'animate-out slide-out-to-right-full fade-out-0',
                    className
                )}
                role="alert"
                {...props}
            >
                {duration && onClose && (
                    <div className="absolute top-0 left-0 right-0 h-1 bg-black/10 dark:bg-white/10 overflow-hidden">
                        <div
                            className="h-full bg-black/30 dark:bg-white/30 animate-nb-shrink"
                            style={{ animationDuration: `${duration}ms` }}
                        />
                    </div>
                )}

                <div className="flex items-start gap-4 p-4 pt-5">
                    {(icon || defaultIcon) && (
                        <div className="flex-shrink-0 mt-0.5">{icon || defaultIcon}</div>
                    )}

                    <div className="flex-1 min-w-0">
                        {title && <p className="font-black text-base leading-tight">{title}</p>}
                        {description && (
                            <p className="font-medium text-sm mt-1 opacity-80 leading-snug">
                                {description}
                            </p>
                        )}
                        {children}

                        {action && <div className="mt-3">{action}</div>}
                    </div>

                    {onClose && (
                        <button
                            type="button"
                            onClick={() => {
                                setIsLeaving(true);
                                setTimeout(() => onClose(), 200);
                            }}
                            className={cn(
                                'flex-shrink-0 h-8 w-8 flex items-center justify-center',
                                'border-2 border-brutal',
                                'bg-white dark:bg-gray-900',
                                'text-black dark:text-white',
                                'shadow-brutal-sm',
                                'transition-all duration-150',
                                'hover:shadow-brutal-sm hover:translate-x-0.5 hover:translate-y-0.5',
                                'active:shadow-none active:translate-x-1 active:translate-y-1',
                                'focus:outline-none focus:ring-2 focus:ring-black dark:focus:ring-white focus:ring-offset-2'
                            )}
                            aria-label="Close"
                        >
                            <X className="h-4 w-4 stroke-[3]" />
                        </button>
                    )}
                </div>
            </div>
        );
    }
);
Toast.displayName = 'Toast';

interface ToastContainerProps extends React.HTMLAttributes<HTMLDivElement> {
    position?:
        | 'top-left'
        | 'top-center'
        | 'top-right'
        | 'bottom-left'
        | 'bottom-center'
        | 'bottom-right';
}

const ToastContainer = React.forwardRef<HTMLDivElement, ToastContainerProps>(
    ({ className, position = 'bottom-right', children, ...props }, ref) => {
        const positionClasses = {
            'top-left': 'top-4 left-4 items-start',
            'top-center': 'top-4 left-1/2 -translate-x-1/2 items-center',
            'top-right': 'top-4 right-4 items-end',
            'bottom-left': 'bottom-4 left-4 items-start',
            'bottom-center': 'bottom-4 left-1/2 -translate-x-1/2 items-center',
            'bottom-right': 'bottom-4 right-4 items-end',
        };

        return (
            <div
                ref={ref}
                className={cn(
                    'fixed z-50 flex flex-col gap-3 pointer-events-none p-4',
                    positionClasses[position],
                    className
                )}
                {...props}
            >
                {children}
            </div>
        );
    }
);
ToastContainer.displayName = 'ToastContainer';

interface ToastItem {
    id: string;
    variant?: ToastProps['variant'];
    title?: string;
    description?: string;
    duration?: number;
    action?: React.ReactNode;
}

function useToast() {
    const [toasts, setToasts] = React.useState<ToastItem[]>([]);

    const addToast = React.useCallback((toast: Omit<ToastItem, 'id'>) => {
        const id = Math.random().toString(36).substring(2, 11);
        setToasts((prev) => [...prev, { ...toast, id }]);
        return id;
    }, []);

    const removeToast = React.useCallback((id: string) => {
        setToasts((prev) => prev.filter((toast) => toast.id !== id));
    }, []);

    const clearToasts = React.useCallback(() => {
        setToasts([]);
    }, []);

    const success = React.useCallback(
        (title: string, description?: string) => {
            return addToast({ variant: 'success', title, description });
        },
        [addToast]
    );

    const error = React.useCallback(
        (title: string, description?: string) => {
            return addToast({ variant: 'error', title, description });
        },
        [addToast]
    );

    const warning = React.useCallback(
        (title: string, description?: string) => {
            return addToast({ variant: 'warning', title, description });
        },
        [addToast]
    );

    const info = React.useCallback(
        (title: string, description?: string) => {
            return addToast({ variant: 'info', title, description });
        },
        [addToast]
    );

    return {
        toasts,
        addToast,
        removeToast,
        clearToasts,
        success,
        error,
        warning,
        info,
    };
}

export { Toast, ToastContainer, useToast, toastVariants };
export type { ToastContainerProps, ToastItem };
