// packages/ui/src/components/waitlist-page/WaitlistPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Sparkles, Users, Star } from 'lucide-vue-next'
import { cn } from '../../lib/utils'
import Button from '../button/Button.vue'
import Input from '../input/Input.vue'

interface WaitlistPageProps {
    title?: string
    description?: string
    ctaText?: string
    waitlistCount?: number
    class?: string
}

const props = withDefaults(defineProps<WaitlistPageProps>(), {
    title: 'Join the BrutxUI Waitlist Club',
    description: '',
    ctaText: 'Secure Priority Access',
    waitlistCount: 0,
    class: '',
})

const emit = defineEmits<{
    submit: [email: string]
}>()

const email = ref('')

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

const rootClasses = computed(() => cn('w-full max-w-lg mx-auto text-center', props.class))

function handleSubmit() {
    if (email.value && EMAIL_REGEX.test(email.value)) {
        emit('submit', email.value)
    }
}
</script>

<template>
    <div :class="rootClasses">
        <div class="inline-flex items-center gap-2 mb-6 bg-brutal-accent px-3 py-1 border-3 border-brutal rotate-[-1deg]">
            <Sparkles class="h-4 w-4 stroke-[3] animate-spin" />
            <span class="font-black text-sm">Early Access</span>
        </div>

        <h1 class="text-3xl font-black tracking-tight">
{{ title }}
</h1>
        <p v-if="description" class="mt-3 text-brutal-muted-foreground font-medium">
{{ description }}
</p>

        <form class="mt-8 flex flex-col sm:flex-row gap-3" @submit.prevent="handleSubmit">
            <Input v-model="email" type="email" placeholder="you@example.com" class="flex-1" />
            <Button type="submit" variant="primary">
{{ ctaText }}
</Button>
        </form>

        <div class="mt-8 flex items-center justify-center gap-6 text-sm font-bold text-brutal-muted-foreground">
            <div v-if="waitlistCount > 0" class="flex items-center gap-1">
                <Users class="h-4 w-4 stroke-[3]" />
                <span>{{ waitlistCount.toLocaleString() }} on waitlist</span>
            </div>
            <div class="flex items-center gap-1">
                <Star v-for="i in 5" :key="i" class="h-3 w-3 fill-brutal-accent text-brutal-accent" />
            </div>
            <div class="flex items-center gap-1">
                <div class="h-2 w-2 rounded-full bg-brutal-success animate-pulse" />
                <span>Live</span>
            </div>
        </div>
    </div>
</template>

// packages/ui/src/components/waitlist-page.tsx
import * as React from 'react';
import { Sparkles, Users, Star } from 'lucide-react';
import { Button } from './button';
import { Input } from './input';

export interface WaitlistPageProps extends React.HTMLAttributes<HTMLDivElement> {
    title?: string;
    description?: string;
    ctaText?: string;
    onWaitlistSubmit?: (e: React.FormEvent<HTMLFormElement>, email: string) => void;
}

export function WaitlistPage({
    title = 'Join the BrutxUI Waitlist Club',
    description = 'Get early developer keys to copy premium blocks, customized theme presets, and unlock deep registry CLI integrations before everyone else.',
    ctaText = 'Secure Priority Access',
    onWaitlistSubmit,
    className,
    ...props
}: WaitlistPageProps) {
    const [email, setEmail] = React.useState('');

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (onWaitlistSubmit) onWaitlistSubmit(e, email);
    };

    return (
        <section
            className={`w-full py-16 md:py-24 bg-brutal-bg text-brutal-fg border-3 border-brutal transition-colors duration-200 ${className || ''}`}
            {...props}
        >
            <div className="container px-4 md:px-6 mx-auto max-w-4xl">
                <div className="flex flex-col items-center justify-center text-center space-y-8">
                    <div className="inline-flex items-center space-x-2 bg-brutal-accent text-black px-4 py-1.5 border-3 border-brutal font-black text-xs uppercase tracking-wider rotate-[-1.5deg]">
                        <Sparkles className="h-4 w-4 stroke-[3] animate-spin" />
                        <span>Private Beta Access Open</span>
                    </div>

                    <div className="space-y-4">
                        <h1 className="text-4xl font-black tracking-tight sm:text-5xl md:text-6xl leading-[1.05]">
                            {title}
                        </h1>
                        <p className="max-w-[640px] text-lg font-bold text-gray-700 dark:text-gray-300 mx-auto leading-relaxed">
                            {description}
                        </p>
                    </div>

                    <form
                        onSubmit={handleSubmit}
                        className="w-full max-w-md flex flex-col sm:flex-row gap-3 pt-2"
                    >
                        <Input
                            type="email"
                            placeholder="Enter your personal email..."
                            required
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className="flex-grow text-base py-6 bg-white dark:bg-gray-800"
                        />
                        <Button
                            type="submit"
                            variant="primary"
                            className="font-black text-sm py-6 px-6 shrink-0"
                        >
                            {ctaText}
                        </Button>
                    </form>

                    <div className="w-full border-t-3 border-brutal pt-8 mt-6">
                        <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 items-center justify-center max-w-2xl mx-auto">
                            <div className="flex items-center justify-center space-x-2 font-black text-sm">
                                <Users className="h-5 w-5 text-brutal-secondary stroke-[2.5]" />
                                <span>1,840+ Developers on waitlist</span>
                            </div>
                            <div className="flex items-center justify-center space-x-1 font-black text-sm">
                                {[...Array(5)].map((_, i) => (
                                    <Star key={i} className="h-4 w-4 fill-brutal-accent text-black stroke-[2.5]" />
                                ))}
                                <span className="pl-1">4.9/5 stars rating</span>
                            </div>
                            <div className="flex items-center justify-center space-x-2 font-black text-sm sm:col-span-2 md:col-span-1">
                                <span className="h-2 w-2 rounded-full bg-brutal-success animate-ping" />
                                <span>Beta Invites sent daily</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}
