// packages/ui/src/components/pagination.tsx
'use client';

import * as React from 'react';
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../lib/utils';

const paginationVariants = cva('flex items-center justify-center', {
    variants: {
        variant: {
            default: '',
            rounded: '[&_button]:rounded-none',
            minimal: '[&_button]:border-0 [&_button]:shadow-none',
        },
        size: {
            sm: 'gap-1',
            default: 'gap-2',
            lg: 'gap-3',
        },
    },
    defaultVariants: {
        variant: 'default',
        size: 'default',
    },
});

const paginationButtonVariants = cva(
    [
        'inline-flex items-center justify-center font-black',
        'border-3 border-brutal',
        'transition-all duration-150',
        'focus:outline-none focus:ring-2 focus:ring-black dark:focus:ring-white focus:ring-offset-2',
        'disabled:opacity-40 disabled:cursor-not-allowed disabled:transform-none disabled:shadow-none',
    ],
    {
        variants: {
            size: {
                sm: 'h-8 min-w-8 text-sm px-2',
                default: 'h-10 min-w-10 text-base px-3',
                lg: 'h-12 min-w-12 text-lg px-4',
            },
            isActive: {
                true: [
                    'bg-black text-white dark:bg-white dark:text-black',
                    'shadow-[4px_4px_0px_0px_#FF6B6B]',
                    'hover:shadow-[2px_2px_0px_0px_#FF6B6B]',
                    'active:shadow-none active:translate-x-1 active:translate-y-1',
                ],
                false: [
                    'bg-white dark:bg-gray-900 text-black dark:text-white',
                    'shadow-brutal',
                    'hover:bg-gray-100 dark:hover:bg-gray-800',
                    'hover:shadow-brutal-sm',
                    'active:shadow-none active:translate-x-1 active:translate-y-1',
                ],
            },
        },
        defaultVariants: {
            size: 'default',
            isActive: false,
        },
    }
);

interface PaginationProps
    extends React.HTMLAttributes<HTMLElement>,
        VariantProps<typeof paginationVariants> {
    currentPage: number;
    totalPages: number;
    onPageChange: (page: number) => void;
    siblingCount?: number;
    showFirstLast?: boolean;
    showPageNumbers?: boolean;
}

const Pagination = React.forwardRef<HTMLElement, PaginationProps>(
    (
        {
            className,
            currentPage,
            totalPages,
            onPageChange,
            siblingCount = 1,
            showFirstLast = true,
            showPageNumbers = true,
            variant,
            size,
            ...props
        },
        ref
    ) => {
        const range = (start: number, end: number) => {
            const length = end - start + 1;
            return Array.from({ length }, (_, idx) => idx + start);
        };

        const paginationRange = React.useMemo(() => {
            const totalPageNumbers = siblingCount + 5;

            if (totalPageNumbers >= totalPages) {
                return range(1, totalPages);
            }

            const leftSiblingIndex = Math.max(currentPage - siblingCount, 1);
            const rightSiblingIndex = Math.min(currentPage + siblingCount, totalPages);

            const shouldShowLeftDots = leftSiblingIndex > 2;
            const shouldShowRightDots = rightSiblingIndex < totalPages - 2;

            const firstPageIndex = 1;
            const lastPageIndex = totalPages;

            if (!shouldShowLeftDots && shouldShowRightDots) {
                const leftItemCount = 3 + 2 * siblingCount;
                const leftRange = range(1, leftItemCount);
                return [...leftRange, 'dots', totalPages];
            }

            if (shouldShowLeftDots && !shouldShowRightDots) {
                const rightItemCount = 3 + 2 * siblingCount;
                const rightRange = range(totalPages - rightItemCount + 1, totalPages);
                return [firstPageIndex, 'dots', ...rightRange];
            }

            if (shouldShowLeftDots && shouldShowRightDots) {
                const middleRange = range(leftSiblingIndex, rightSiblingIndex);
                return [firstPageIndex, 'dots', ...middleRange, 'dots', lastPageIndex];
            }

            return range(1, totalPages);
        }, [totalPages, siblingCount, currentPage]);

        const buttonSize = size || 'default';

        return (
            <nav
                ref={ref}
                role="navigation"
                aria-label="pagination"
                className={cn(paginationVariants({ variant, size, className }))}
                {...props}
            >
                {showFirstLast && (
                    <button
                        type="button"
                        className={cn(
                            paginationButtonVariants({ size: buttonSize, isActive: false })
                        )}
                        onClick={() => onPageChange(1)}
                        disabled={currentPage === 1}
                        aria-label="Go to first page"
                    >
                        <ChevronsLeft className="h-4 w-4 stroke-[3]" />
                    </button>
                )}

                <button
                    type="button"
                    className={cn(paginationButtonVariants({ size: buttonSize, isActive: false }))}
                    onClick={() => onPageChange(currentPage - 1)}
                    disabled={currentPage === 1}
                    aria-label="Go to previous page"
                >
                    <ChevronLeft className="h-4 w-4 stroke-[3]" />
                </button>

                {showPageNumbers &&
                    paginationRange.map((pageNumber, index) => {
                        if (pageNumber === 'dots') {
                            return (
                                <span
                                    key={`dots-${index}`}
                                    className={cn(
                                        'flex items-center justify-center font-black text-black dark:text-white',
                                        buttonSize === 'sm' && 'h-8 w-8',
                                        buttonSize === 'default' && 'h-10 w-10',
                                        buttonSize === 'lg' && 'h-12 w-12'
                                    )}
                                >
                                    •••
                                </span>
                            );
                        }

                        return (
                            <button
                                key={pageNumber}
                                type="button"
                                className={cn(
                                    paginationButtonVariants({
                                        size: buttonSize,
                                        isActive: currentPage === pageNumber,
                                    })
                                )}
                                onClick={() => onPageChange(pageNumber as number)}
                                aria-label={`Go to page ${pageNumber}`}
                                aria-current={currentPage === pageNumber ? 'page' : undefined}
                            >
                                {pageNumber}
                            </button>
                        );
                    })}

                {!showPageNumbers && (
                    <span className="px-4 font-black text-black dark:text-white">
                        {currentPage} / {totalPages}
                    </span>
                )}

                <button
                    type="button"
                    className={cn(paginationButtonVariants({ size: buttonSize, isActive: false }))}
                    onClick={() => onPageChange(currentPage + 1)}
                    disabled={currentPage === totalPages}
                    aria-label="Go to next page"
                >
                    <ChevronRight className="h-4 w-4 stroke-[3]" />
                </button>

                {showFirstLast && (
                    <button
                        type="button"
                        className={cn(
                            paginationButtonVariants({ size: buttonSize, isActive: false })
                        )}
                        onClick={() => onPageChange(totalPages)}
                        disabled={currentPage === totalPages}
                        aria-label="Go to last page"
                    >
                        <ChevronsRight className="h-4 w-4 stroke-[3]" />
                    </button>
                )}
            </nav>
        );
    }
);
Pagination.displayName = 'Pagination';

export { Pagination, paginationVariants, paginationButtonVariants };
export type { PaginationProps };

// packages/ui/src/components/pagination/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue'
import { type VariantProps } from 'class-variance-authority'
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from '@lucide/vue'
import { cn } from '../../lib/utils'
import { paginationVariants, paginationButtonVariants } from './pagination-variants'
import { iconSizeVariants, type IconSize } from '../../lib/icon-size-variants'
import { useLocale } from '@/composables/useLocale'

const { t } = useLocale()

type PaginationVariantProps = VariantProps<typeof paginationVariants>

const FIRST_PAGE = 1
const MIN_PAGE_THRESHOLD = 2
const FIRST_PAGES_COUNT = 3
const ELLIPSIS_COUNT = 1

interface PaginationProps {
    currentPage: number
    totalPages: number
    siblingCount?: number
    showFirstLast?: boolean
    showPageNumbers?: boolean
    variant?: NonNullable<PaginationVariantProps['variant']>
    size?: NonNullable<PaginationVariantProps['size']>
    class?: string
}

const props = withDefaults(defineProps<PaginationProps>(), {
    siblingCount: 1,
    showFirstLast: true,
    showPageNumbers: true,
    variant: 'default',
    size: 'default',
    class: undefined,
})

const emit = defineEmits<{
    'update:currentPage': [page: number]
    jump: []
}>()

function range(start: number, end: number) {
    const length = end - start + 1
    return Array.from({ length }, (_, idx) => idx + start)
}

const paginationRange = computed(() => {
    if (props.totalPages <= 0) return []

    const totalPageNumbers = props.siblingCount * 2 + FIRST_PAGES_COUNT + ELLIPSIS_COUNT * 2

    if (totalPageNumbers >= props.totalPages) {
        return range(FIRST_PAGE, props.totalPages)
    }

    const leftSiblingIndex = Math.max(props.currentPage - props.siblingCount, FIRST_PAGE)
    const rightSiblingIndex = Math.min(props.currentPage + props.siblingCount, props.totalPages)

    const shouldShowLeftDots = leftSiblingIndex > MIN_PAGE_THRESHOLD
    const shouldShowRightDots = rightSiblingIndex < props.totalPages - MIN_PAGE_THRESHOLD

    const lastPageIndex = props.totalPages

    if (!shouldShowLeftDots && shouldShowRightDots) {
        const leftEndIndex = FIRST_PAGES_COUNT + 2 * props.siblingCount
        const leftRange = range(FIRST_PAGE, leftEndIndex)
        return [...leftRange, 'dots' as const, props.totalPages]
    }

    if (shouldShowLeftDots && !shouldShowRightDots) {
        const rightEndIndex = FIRST_PAGES_COUNT + 2 * props.siblingCount
        const rightRange = range(props.totalPages - rightEndIndex + 1, props.totalPages)
        return [FIRST_PAGE, 'dots' as const, ...rightRange]
    }

    if (shouldShowLeftDots && shouldShowRightDots) {
        const middleRange = range(leftSiblingIndex, rightSiblingIndex)
        return [FIRST_PAGE, 'dots' as const, ...middleRange, 'dots' as const, lastPageIndex]
    }

    return range(FIRST_PAGE, props.totalPages)
})

const navClasses = computed(() =>
    cn(paginationVariants({ variant: props.variant, size: props.size }), props.class)
)

const safeCurrentPage = computed(() =>
    Math.min(Math.max(props.currentPage, FIRST_PAGE), Math.max(props.totalPages, FIRST_PAGE))
)

const PAGINATION_SIZE_TO_ICON: Record<NonNullable<PaginationVariantProps['size']>, IconSize> = {
    sm: 'sm',
    default: 'default',
    lg: 'lg',
}

const iconClasses = computed(() =>
    cn(iconSizeVariants({ size: PAGINATION_SIZE_TO_ICON[props.size] }))
)

const dotsSizeClasses = computed(() => {
    if (props.size === 'sm') return 'h-8 w-8'
    if (props.size === 'lg') return 'h-12 w-12'
    return 'h-10 w-10'
})

const firstButtonClasses = computed(() =>
    cn(paginationButtonVariants({ size: props.size, isActive: false }))
)

const prevButtonClasses = computed(() =>
    cn(paginationButtonVariants({ size: props.size, isActive: false }))
)

const nextButtonClasses = computed(() =>
    cn(paginationButtonVariants({ size: props.size, isActive: false }))
)

const lastButtonClasses = computed(() =>
    cn(paginationButtonVariants({ size: props.size, isActive: false }))
)

const dotsClasses = computed(() =>
    cn(
        'flex items-center justify-center font-black text-brutal-fg cursor-pointer',
        'hover:bg-brutal-muted transition-colors duration-150',
        'focus:outline-none focus:ring-2 focus:ring-brutal-ring focus:ring-offset-2',
        dotsSizeClasses.value
    )
)

const pageButtonActiveClasses = computed(() =>
    cn(paginationButtonVariants({ size: props.size, isActive: true }))
)

const pageButtonInactiveClasses = computed(() =>
    cn(paginationButtonVariants({ size: props.size, isActive: false }))
)

function onPageChange(page: number) {
    if (page >= FIRST_PAGE && page <= props.totalPages) {
        emit('update:currentPage', page)
    }
}
</script>

<template>
    <nav role="navigation" :aria-label="t('pagination.label')" :class="navClasses">
        <button
            v-if="showFirstLast"
            type="button"
            :class="firstButtonClasses"
            :disabled="safeCurrentPage <= FIRST_PAGE"
            :aria-label="t('pagination.firstPage')"
            @click="onPageChange(1)"
        >
            <ChevronsLeft :class="iconClasses" />
        </button>

        <button
            type="button"
            :class="prevButtonClasses"
            :disabled="safeCurrentPage <= FIRST_PAGE"
            :aria-label="t('pagination.previousPage')"
            @click="onPageChange(safeCurrentPage - 1)"
        >
            <ChevronLeft :class="iconClasses" />
        </button>

        <template v-if="showPageNumbers">
            <template v-for="(pageNumber, index) in paginationRange" :key="index">
                <button
                    v-if="pageNumber === 'dots'"
                    type="button"
                    :class="dotsClasses"
                    :aria-label="t('pagination.jumpPages')"
                    @click="emit('jump')"
                >
                    •••
                </button>
                <button
                    v-else
                    type="button"
                    :class="safeCurrentPage === pageNumber ? pageButtonActiveClasses : pageButtonInactiveClasses"
                    :aria-label="t('pagination.page', { number: pageNumber as number })"
                    :aria-current="safeCurrentPage === pageNumber ? 'page' : undefined"
                    @click="onPageChange(pageNumber as number)"
                >
                    {{ pageNumber }}
                </button>
            </template>
        </template>

        <span v-if="!showPageNumbers" class="px-4 font-black text-brutal-fg">
            {{ safeCurrentPage }} / {{ totalPages }}
        </span>

        <button
            type="button"
            :class="nextButtonClasses"
            :disabled="safeCurrentPage >= props.totalPages"
            :aria-label="t('pagination.nextPage')"
            @click="onPageChange(safeCurrentPage + 1)"
        >
            <ChevronRight :class="iconClasses" />
        </button>

        <button
            v-if="showFirstLast"
            type="button"
            :class="lastButtonClasses"
            :disabled="safeCurrentPage >= props.totalPages"
            :aria-label="t('pagination.lastPage')"
            @click="onPageChange(totalPages)"
        >
            <ChevronsRight :class="iconClasses" />
        </button>
    </nav>
</template>
